import { type NextPage } from "next";
import Head from "next/head";
import { useSession } from "next-auth/react";
import { api } from "~/utils/api";

import Landing from "../components/landing";
import HomePage from "../components/home";
import Loading from "~/components/home/Loading";

const Home: NextPage = () => {
  const { data, status } = useSession();

  if (status === "loading") {
    return <Loading />;
  }

  return (
    <>
      <Head>
        <title>PollHub</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {data ? (
        <HomePage />
      ) : (
        <main className="flex min-h-screen flex-col items-center justify-center ">
          <Landing />
        </main>
      )}
    </>
  );
};

export default Home;
